//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TranscendenceRL.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TranscendenceRL.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What was it the Orator give you?
        ///Visions of a different universe?
        ///Of a universe drastically changed?
        ///Or of one reconstructed entirely? +
        ///
        ///...In a time far beyond what
        ///mankind currently knows as time,
        ///where the reality is familiar but
        ///altogether remade new entirely,
        ///a different mankind grows out of
        ///the metaphorical ashes of our
        ///own mortal era...
        ///                                
        ///...But only those who are willing
        ///to meet the Orator at their home
        ///in the Galactic Core are worthy
        ///of witnessing the [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Crawl {
            get {
                return ResourceManager.GetString("Crawl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;======&gt;  /=====&gt;   /======\  /&gt;    /|  |&gt;=====&gt;  /&gt;=====&gt;  |&gt;=====&gt;  /&gt;    /|  |&gt;===&gt;    |&gt;=====&gt;  /&gt;    |\  /&gt;=====&gt;  |&gt;=====&gt;
        ///   ||     ||    ||  ||    ||  ||\   ||  ||        ||        ||        ||\   ||  ||   =&gt;   ||        ||\   ||  ||        ||      
        ///   ||     |&gt;====&gt;   |&gt;====&lt;|  || \  ||  |&gt;====&lt;|  ||        |&gt;=====&gt;  || \  ||  ||    =&gt;  |&gt;=====&gt;  || \  ||  ||        |&gt;=====&gt;
        ///   ||     || \\     ||    ||  ||  \ ||        ||  ||        ||        ||  \ ||  ||   =&gt;   ||        ||  \ ||  ||        || [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
